apiVersion: v1
kind: Service
metadata:
  name: {{.chart.name}}
  labels:
    app: {{.chart.name}}
spec:
  ports:
  - port: {{.values.service.port}}
    targetPort: {{.values.service.targetPort}}
    protocol: TCP
  selector:
    app: {{.chart.name}}
  type: {{.values.service.type}}